### PR TITLE
Traverse recursively condition tree components

### PR DESCRIPTION
**Pull request by abbradar**
This should fix jailbreaking dependencies inside conditionals.

### CODE REVIEW

**Comment by abbradar** [comment]
This has fixed Agda build for me on `nixpkgs master` and GHC 7.8

**Comment by abbradar** [comment]
Ouch, I had't done enough research before making a PR and saw https://github.com/peti/jailbreak-cabal/commit/99eac40deb481b185fd93fd307625369ff5e1ec0 now. I guess that means this change is out of question then! Maybe we can mention this in the README to prevent future misunderstandings?

**Comment by peti** [comment]
There's also https://github.com/peti/jailbreak-cabal/issues/7 and https://github.com/peti/jailbreak-cabal/pull/4. This issue seems to come up frequently. I guess we should document the rationale for the current behavior in the readme or the source code.

**Comment by abbradar** [comment]
What about a simple comment, like this?

**Comment by peti** [comment]
Very good. Thank you!

**Pull request merged**
